name: ExpressionsProvider
version: '${version}'
authors:
  - 4drian3d
  - Sliman4
main: io.github.miniplaceholders.expressions.paper.PaperPlugin
description: Expressions Provider
api-version: '1.21'
folia-supported: true
dependencies:
  server:
    MiniPlaceholders:
      required: true
